RTC_TOKEN=007eJxTYFj1uuOVbpX1+x6eGcYcYiz/uzO/nYzd+vugbJr2jtSSEDkFBnOzxFRTS+NkQ7M0A5MkiyRLE4PEJMPUNAMzi7Q002QTO/GctIZARgaduNmsjAwQCOJzMyRmZsYnZyTm5aXmMDAAAB9pITQ=



send_data:
	cd agora_rtc_sdk/example/out && \
	./sample_send_h264_pcm --token ${RTC_TOKEN} --channelId aii_channel --videoFile test_data/send_video.h264 --audioFile test_data/send_audio_16k_1ch.pcm

receive_data:
	cd agora_rtc_sdk/example/out && \
	./sample_receive_h264_pcm --token ${RTC_TOKEN} --channelId aii_channel


